import openai
import json
import re # Import regex module

# Configure OpenAI API
openai.api_base = "https://openrouter.ai/api/v1"
openai.api_key = "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"

def get_llm_feedback(plan_code, context_messages):
    """
    Gets feedback on a generated plan from an LLM and extracts improved code if provided.

    Args:
        plan_code (str): The Python code for the generated plan.
        context_messages (list): The list of messages used to generate the plan.

    Returns:
        tuple: A tuple containing (feedback_text: str, improved_code: str or None).
    """
    
    context_str = "\n".join([f"{msg['role']}: {msg['content']}" for msg in context_messages])

    feedback_prompt = f"""You are an expert robotics software engineer and a senior code reviewer. Your task is to evaluate a plan for a robot. The plan is a Python function that uses a specific set of robot skills.

Here is the context provided to the planner LLM:
---
{context_str}
---

Here is the plan generated by the planner LLM:
---
{plan_code}
---

Please evaluate this plan based on the following criteria:
1.  **Accuracy**: Does the plan correctly interpret the user's instruction and achieve the goal?
2.  **Plausibility**: Are the steps in the plan logical and likely to succeed in a real-world environment?
3.  **Efficiency**: Is the plan efficient or are there redundant steps?
4.  **Safety**: Does the plan consider potential risks and include safety measures?

Provide your feedback in a structured format. Start with a summary of your evaluation, then provide detailed comments on each criterion.

### CRITICAL INSTRUCTION FOR CODE IMPROVEMENTS:
IF AND ONLY IF you are suggesting an improved version of the plan, you MUST enclose the *entire* improved Python function within the XML-like tags `<IMPROVED_CODE>` and `</IMPROVED_CODE>`.
DO NOT include any other text inside these `<IMPROVED_CODE>` tags, only the Python code of the improved function.
If no improvements are needed or suggested, DO NOT include these tags at all.
FAILURE TO FOLLOW THIS INSTRUCTION WILL RESULT IN THE IMPROVED CODE NOT BEING APPLIED.
"""

    feedback_messages = [
        {"role": "user", "content": feedback_prompt}
    ]

    try:
        response = openai.ChatCompletion.create(
            model="gpt-4o-mini-2024-07-18",
            messages=feedback_messages,
            max_tokens=1500, # Increased max_tokens to allow for detailed feedback and code
            temperature=0.1,
            stop=None
        )
        full_feedback_response = response.choices[0].message['content'].strip()

        # Try to find <IMPROVED_CODE> tags first
        improved_code_match_tags = re.search(r'<IMPROVED_CODE>(.*?)</IMPROVED_CODE>', full_feedback_response, re.DOTALL)
        
        improved_code = None
        feedback_text = full_feedback_response

        if improved_code_match_tags:
            improved_code = improved_code_match_tags.group(1).strip()
            # Ensure any markdown fences within the XML tags are also removed if the LLM put them there
            improved_code = re.sub(r'```python\s*|```', '', improved_code).strip()
            feedback_text = full_feedback_response.replace(improved_code_match_tags.group(0), "").strip()
        else:
            # If tags not found, try to find "### Improved Plan" and assume the following is code
            improved_code_pattern_start = re.search(r'### Improved Plan', full_feedback_response)
            if improved_code_pattern_start:
                # Extract everything after "### Improved Plan"
                potential_code = full_feedback_response[improved_code_pattern_start.end():].strip()
                # Strip markdown code fences if they exist
                improved_code = re.sub(r'```python\s*|```', '', potential_code).strip()
                # Keep the feedback text but remove the potential code part if it was successfully extracted
                feedback_text = full_feedback_response[:improved_code_pattern_start.start()].strip()
            else:
                feedback_text = full_feedback_response # Fallback if no specific pattern is found

        return feedback_text, improved_code

    except Exception as e:
        return f"Error getting feedback: {e}", None

if __name__ == '__main__':
    # This is for testing the feedback function directly
    # You would need to provide example plan_code and context_messages
    
    example_plan = """

def find_and_pick_up_apple():
    # Rotate to find an apple
    for _ in range(4):
        event = controller.step(action="RotateRight")
        if 'Apple' in [obj['objectType'] for obj in event.metadata['objects']]:
            break
    # Move towards the apple
    controller.step(action="MoveAhead")
    # Pick up the apple
    controller.step(action="PickupObject", objectId="Apple|1")
"""
    
    example_context = [
        {"role": "user", "content": "Find an apple and pick it up."},
        {"role": "system", "content": "You are a helpful robot assistant."}
    ]

    feedback_text, improved_code = get_llm_feedback(example_plan, example_context)
    print("--- LLM Feedback ---")
    print(feedback_text)
    print("--------------------")
    if improved_code:
        print("\n--- Suggested Improved Code ---")
        print(improved_code)
        print("-------------------------------")